services:
  lb:
    image: doodkin/tinylb:0.1.0
    container_name: tinylb
    ports:
      - "8443:8443"
    volumes:
      - ./lb.toml:/etc/tinylb/lb.toml:ro
      - ./certs:/etc/tinylb/certs:ro
    command: ["/usr/local/bin/tinylb", "/etc/tinylb/lb.toml"]
    depends_on:
      - backend-a
      - backend-b
    restart: unless-stopped

  backend-a: { image: traefik/whoami:v1.10, command: ["--port=80", "--name=backend-a"], restart: unless-stopped }
  backend-b: { image: traefik/whoami:v1.10, command: ["--port=80", "--name=backend-b"], restart: unless-stopped }
